<?xml version="1.0" encoding="UTF-8"?>
<project name="PlantUML client" default="help">

  <property name="dc.project-name" value="plantuml-client"/>


  <target name="setup" depends="composer:install,plantuml:generate"/>
  <target name="qa" depends="composer:validate,cs:check,phpstan:check,dc:up,phpunit:check"/>


  <target name="dc:up" description="Launch containers">
    <exec executable="docker" passthru="true" checkreturn="true">
      <arg value="compose"/>
      <arg line="--project-name ${dc.project-name}"/>
      <arg value="up"/>
      <arg line="--detach --remove-orphans"/>
    </exec>
  </target>

  <target name="dc:stop" description="Stop containers">
    <exec executable="docker" passthru="true">
      <arg value="compose"/>
      <arg line="--project-name ${dc.project-name}"/>
      <arg value="stop"/>
    </exec>
  </target>


  <target name="phpunit:check" description="Run unitary tests">
    <exec executable="vendor/bin/phpunit" checkreturn="true" passthru="true">
      <env key="XDEBUG_MODE" value="coverage"/>
    </exec>
  </target>

  <target name="plantuml:generate" description="Generate images from *.puml diagrams">
    <exec executable="plantuml" passthru="true" checkreturn="true">
      <arg path="docs/images/*.puml"/>
      <arg value="-tsvg"/>
      <arg value="-nometadata"/>
    </exec>
    <exec executable="plantuml" passthru="true" checkreturn="true">
      <arg path="docs/images/*.puml"/>
      <arg value="-tpng"/>
      <arg value="-nometadata"/>
    </exec>
  </target>

  <target name="composer:install" description="Install dependencies">
    <composer command="install">
      <arg value="--no-interaction"/>
      <arg value="--prefer-dist"/>
      <arg value="--ansi"/>
    </composer>
  </target>

  <target name="composer:validate" description="Validates composer.json">
    <composer command="validate">
      <arg value="--no-interaction"/>
      <arg value="--strict"/>
      <arg value="--ansi"/>
    </composer>
  </target>

  <target name="phpstan:check" description="Analyse at max level">
    <exec executable="vendor/bin/phpstan" passthru="true" checkreturn="true">
      <arg line="--level=max"/>
      <arg value="analyze"/>
      <arg path="src"/>
      <arg value="--no-progress"/>
      <arg value="--ansi"/>
    </exec>
  </target>

  <target name="mkdocs:serve" depends="plantuml:generate" description="Run the builtin development server">
    <exec executable="mkdocs" passthru="true" checkreturn="true">
      <arg value="serve"/>
    </exec>
  </target>

  <target name="mkdocs:gh-deploy" depends="plantuml:generate" description="Deploy documentation to GitHub Pages">
    <exec executable="mkdocs" passthru="true" checkreturn="true">
      <arg value="gh-deploy"/>
    </exec>
  </target>

  <target name="help">
    <visualizer/>
    <exec executable="xdg-open" spawn="true">
      <arg file="build.png"/>
    </exec>
  </target>

  <target name="cs:fix" description="Fixes code style in src dir.">
    <exec executable="vendor/bin/php-cs-fixer" passthru="true" checkreturn="true">
      <arg line="--ansi --no-interaction --verbose"/>
      <arg value="fix"/>
    </exec>
  </target>

  <target name="cs:check" description="Checks if configured files/directories comply with configured rules.">
    <exec executable="vendor/bin/php-cs-fixer" passthru="true" checkreturn="true">
      <arg line="--ansi --no-interaction --verbose"/>
      <arg value="check"/>
    </exec>
  </target>

</project>
