name: CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: $HOME/.cache/composer
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.3
          version: 2

      # https://github.com/PhpGt/Database/blob/master/.github/workflows/ci.yml
      - name: Archive build
        run: mkdir /tmp/github-actions/ && tar -cvf /tmp/github-actions/build.tar ./

      - name: Upload build archive for test runners
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

  phpstan:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xf /tmp/github-actions/build.tar ./

      - name: Phing Build
        uses: phingofficial/phing-github-action@main
        with:
          version: 3.0.0-rc1
          targets: phpstan:analyze

  phpunit:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: /tmp/github-actions

      - name: Extract build archive
        run: tar -xf /tmp/github-actions/build.tar ./

      - name: Phing Build
        uses: phingofficial/phing-github-action@main
        with:
          version: 3.0.0-rc1
          targets: phpunit:test

